### ISSUE TITLE
Support for unbounded intervals

### ISSUE THREAD

**Issue by homeworkprod** [kvesteri/intervals#21]
I'd like to see support for intervals which only define either a lower or upper boundary.

Examples include a shop article that is available only until a certain date (like a discontinued product), or only starting on a certain date (like a newly introduced product). The article would include both a lifetime start date and end date. Making it available for a limited period of time already works (using an interval with two boundaries) as would making it available forever (both start date and end date not being set; this doesn't have to be modeled as an interval, though, as it can be handled before doing any interval membership tests).

**Comment by kvesteri** [comment]
This is supported now.

**Comment by homeworkprod** [comment]
Hey @kvesteri, nice to hear that!

Would you mind pointing me to the relevant documentation and/or commits? I didn't find anything related to that.

**Comment by kvesteri** [comment]
I added docs for those. Check the updated readme.
