### ISSUE TITLE
Error in DateInterval

### ISSUE THREAD

**Issue by usakov-leonid** [kvesteri/intervals#27]
Hi, I catch error, when I do:
from intervals import DateInterval, inf
DateInterval(['2000-01-01', inf])

on 195 line in __init__ you try make:

    def coerce_string(self, value):
        return self.type(value)

and self.type == datetime.date, and value == '2000-01-01' :)

I install intervals from pypi, v0.3.1

**Comment by kvesteri** [comment]
Correct format is:
```python
DateInterval([date(2011, 1, 1), inf])
```
