### ISSUE TITLE
Problem using SQLAlchemy and calling history

### ISSUE THREAD

**Issue by fmerges** [kvesteri/intervals#28]
Hello,

I have a problem with intervals and SQLAlchemy, I'm tracking changes to objects via the history, so when I try to insert a new DateRange it fails because it's comparing a DateInterval() object with a symbol('NO_VALUE'), which then tries to create a DateInterval("[symbol('NO_VALUE'), symbol('NO_VALUE')]") which of course fails with:

TypeError: unsupported operand type(s) for +: 'symbol' and 'datetime.timedelta'

Any ideas?

**Comment by kvesteri** [comment]
Now fixed (as of version 0.6.0).
