### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by coreycb** [kvesteri/intervals#51]
Hi, I'm working on packaging this for ubuntu as it is used by sqlalchemy-utils but will have a hard time getting it into main (ie. officially supported) as it currently gives the appearance of having an unmaintained state. I realize that free software isn't free so just putting this out there. :) I know there isn't much new since 0.8.1, however a new release showing that this project supports modern Python 3 versions (we're up to 3.8 now) would be a good way to show that it is still alive and well. Also getting some responses to open issues would be nice to see too. Thanks for listening!

**Comment by kvesteri** [comment]
Version 0.9 released

**Comment by coreycb** [comment]
Thanks
