### ISSUE TITLE
Support for easier initialization of intervals

### ISSUE THREAD

**Issue by adarshk7** [kvesteri/intervals#7]
For example,

IntInterval(3, 5) == IntInterval((3, 5))
and,
IntInterval[3, 5] == IntInterval([3, 5])

**Comment by kvesteri** [comment]
Guava-like factory methods have been added, closing this for now.

**Comment by homeworkprod** [comment]
> Guava-like factory methods have been added […]

@kvesteri, can you please point me to the commit that added this?

**Comment by kvesteri** [comment]
https://github.com/kvesteri/intervals/commit/6cf3218ea73ba46ad69fd9cab85d9642e07bad32

**Comment by homeworkprod** [comment]
Ah, thanks!
